### ISSUE TITLE
Add vote threshold to data model (for measures)

### ISSUE THREAD

**Issue by catrope** [OSVTAC/osv-results-reporter#16]
Some ballot measures require 50%, some require 2/3

**Comment by carl3** [comment]
Several new attributes contained in the json input are now loaded:

contest.approval_required (for measures or retention/recall with yes/no vote)
  - A string that indicates the number of votes of the total for the measure to pass.
    It can be used as '{{approval_required}} Approval Required'. Values in California can be:
      - Majority
      - 2/3
      - 55%

contest.name: international string
  - a name for the contest that can be used in a contest heading. This will be unique across contests.
    The contest name can be a combination of ballot headings, titles, and subtitles needed to identify
    the contest outside of any context.
    Example: "United States Representative District 13"

contest.max_ranked: integer (applies to RCV contests)
   - If present, defines the maximum number of choices in an RCV that can be ranked (3 for SF in prior elections.

contest.choice.choice.winning_status:
  - A more detailed status besides choice.is_successful. Can be:
        'W':'winning'
        'X':'winning_failed_recall'
        'T':'tied',
        'C':'tied_winner',
        'D':'tied_not_winner',
        'R': 'to_runoff',
        'S':'tied_selected_for_runoff',
        'E':'rcv_eliminated',
        'N':'not_winning', '':''
[The single letter codes used internally are converted to the English strings (with _ separators) in the json. Note the current converter does not use codes S or D, and we have no recalls in the sample
data and there is no linked recall replacement for a possible X status.]

contest.choice.is_writein
  - A boolean value indicates this candidate is a write-in and does not appear on ballots.

contest.success
  - For a ballot measure or recall/retention contest, indicates if the measure passed, i.e. number of yes votes exceeds the approval_required. The choices (yes/no) will also have an is_successful
attribute (note the name inconsistency. [We may change the name in the json to be is_successful to be consistent.]

contest.runoff_date
   - If there is a possible runoff, indicates the date for the runoff election

contest.runoff_type:
  - A string indicating there is a runoff and it's type. Can be one of:
    - top_2 = the top 2 candidates always advance to a runoff (e.g. as in a state primary)
    - non_majority = the top 2 candidates advance to a runoff unless one candidate gets a majority
    
    Note that if there are more than 1 elected (n elected) the top_2 would be top n+1 and for nonmajority, any candidate with a majority of ballots cast will be elected (let m be the number of winners), the runoff will have (n-m)+1 candidates, vote for (n-m). This is rare, and not coded, but does exist.

contest.no_voter_precincts
  - A list of precinct IDs that have no registered voters, and are excluded from detailed reporting and for purposes of computing ballot types.

**Comment by carl3** [comment]
A few more attributes were added to the ORR data loader:

id_ext: Contains the complement to id that is used in other systems-- needs upgrading be a list and to include a prefix indicating which external system the ID is for.

precinct.has_no_voters: used for precincts with no registered voters and can be ignored (redundant with election.no_voter_precincts

election.no_voter_precincts: List of precinct IDs with no registered voters. Currently this doesn't have the "PCT" prefix to make an area ID.

heading.heading_text: A paragraph of explanatory text appearing on ballots under a header. (International text string).

choice.sequence: integer = the order of appearance on a ballot. This could change by ballot type. Currently, these are all the same as order of appearance. (Candidate order is rotated by certain districts, so the sequence would change.)

**Comment by catrope** [comment]
Thanks for adding all these! I'll file follow-up issues for using this data in the UI.
