### ISSUE TITLE
Make the contest names stand out more in the summary page

### ISSUE THREAD

**Issue by cjerdonek** [OSVTAC/osv-results-reporter#17]
Make the contest names stand out more in the summary page. Attached is what it currently looks like.

<img width="561" alt="Screen Shot 2019-06-08 at 3 06 15 PM" src="https://user-images.githubusercontent.com/355822/59152737-3166d780-89ff-11e9-85ab-6a3de8f4b853.png">

**Comment by catrope** [comment]
With my patch:
![Screenshot from 2019-07-11 19-20-22](https://user-images.githubusercontent.com/260792/61097656-f6e2c700-a410-11e9-858e-965771dbe13a.png)
