### ISSUE TITLE
Need helper function to return numeric approval required

### ISSUE THREAD

**Issue by carl3** [OSVTAC/osv-results-reporter#25]
The contest.approval_required exists for yes/no votes (measures, recall, retention) and is a printable string, e.g. "{contest.approval_required} Approval Required" is meaningful. [I would advocate simpler representations rather than 50%+1 and long message.] Values are "Majority", \d/\d or \d+%.

In order to draw a threshold line, a property or filter, e.g. approval_required_fraction, should return a numeric value, e.g. .5, .55, .666666666667 so the threshold line can be drawn.

Note for a conditional runoff, there is a 50% threshold (e.g. Superior Court judges), if a candidate gets >50%, then there is no runoff. There is one city in CA that has a conditional runoff for city council with vote for more than 1. In that case, candidates that get >50% of ballots cast are elected, any remaining under 50%, the top n+1 advance to the runoff, where n is remaining seats to be filled. The detailed winning status has this info for all choices.

**Comment by catrope** [comment]
Carl did this in 158b2af6
