### ISSUE TITLE
Add translation files for English phrases in templates

### ISSUE THREAD

**Issue by catrope** [OSVTAC/osv-results-reporter#35]
Use symbolic names in the templates, and have files for each language that map those symbolic names for text. English would be just another translation language.

**Comment by catrope** [comment]
https://pypi.org/project/python-i18n/ seems like a decent library to use

**Comment by cjerdonek** [comment]
This functionality has now been added (via the [`osv-translations`](https://github.com/OSVTAC/osv-translations) submodule and the `TT` template filter). We still need to find and add translations for all of the phrases. We can do that over time once we find people that know each language.
