### ISSUE TITLE
Make "winner" a candidate attribute

### ISSUE THREAD

**Issue by catrope** [OSVTAC/osv-results-reporter#4]
Right now, the data model doesn't indicate whether a candidate is a winner. This can't be computed (easily) from the vote totals, because some elections have multiple winners (e.g. school board), and some ballot measures require more than 50% (e.g. special tax measures require 2/3). Whether a candidate has won should be an attribute in the input data of the results reporter.

**Comment by cjerdonek** [comment]
Closed by: b90aa45821bb04e8f132ec52997d74fd717e4f0e
